name: build-deploy
on:
  push:
    branches:
      - master
env:
  PROJECT_NAME: http-server

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: '1.16.4'
      - run: go build .
      - run: docker build -t ${PROJECT_NAME} .