name: build-deploy
on:
  push:
    branches:
      - master
env:
  PROJECT_NAME: http-server

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-18.04
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-go@v1
        with:
          go-version: '1.16.4'
          
      - name: Build
        run: go build -v ./...
        
      - name: Test
        run: go test -v ./...
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          tag_with_ref: true
