name: build-deploy
on:
  push:
    branches:
      - master
env:
  PROJECT_NAME: http-server

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-18.04
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - uses: actions/setup-go@v1
        with:
          go-version: '1.16.4'
          
      - name: Build
        run: go build -v ./...
        
      - name: Test
        run: go test -v ./...
        
      - name: Docker login
        run: echo $PAT | docker login ghcr.io -u twiggybuffalo --password-stdin
        env: 
          PAT: ${{secrets.PAT}}
        
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: twiggybuffalo/go-http-server:latest
